### ISSUE TITLE
Live demo link

### ISSUE THREAD

**Issue by imahnama** [Psiale/portfolio#3]
1. The link to the live demo in your readme doesn't work. See screenshot below for the error.
2. There is a grammatical error under your ## Project section in your readme "Give a Star if you like it" instead of "Give a start if you like it"
<img width="1407" alt="Screenshot 2020-07-08 at 19 24 11" src="https://user-images.githubusercontent.com/25789009/86944601-a8195b80-c150-11ea-9db1-33e10f076b1d.png">

**Comment by Psiale** [comment]
Thanks for the heads up, I created a new domain and updated the READme with it. 
you can check it here: https://alexis-sanchez-dev.netlify.app/
